#!/bin/sh

# call with 'curl -LO http://ejas.net/mr'

cd
vcsh clone https://github.com/altercation/dotfiles-mr.git mr
echo "'mr setup' to grab github key for knownhosts & gen new ssh keys"
echo "'.mr/available' and '.mr/active' subdirectories for repos"
echo "'mr up' to update mr repos"
